name: leprecon
services:
  web:
    image: jarnoweemen/leprecon
    container_name: web
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      AUTH_HOST: ${AUTH_HOST}
      CLIENT_ID: ${CLIENT_ID}
      ACCOUNT_HOST: ${ACCOUNT_HOST}
      AUDIENCE: ${AUDIENCE}
      CACHE_LOCATION: ${CACHE_LOCATION}
