name: leprecon
services:
  web:
    build: .
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - ./www:/usr/share/nginx/html # Mount static files
      - ./nginx:/etc/nginx/templates # Mount nginx template (includes environment variables)
    network_mode: host
    environment:
      DEFAULT_HOST: http://127.0.0.1:8080/home