name: leprecon
services:
  web:
    image: jarnoweemen/leprecon:1.0.0-web
    container_name: web
    volumes:
      - ./www:/usr/share/nginx/html # Mount static files
      - ./nginx:/etc/nginx/templates # Mount nginx template (includes environment variables)
    network_mode: host
    environment:
      DEFAULT_HOST: ${DEFAULT_HOST}
      AUTH_HOST: ${AUTH_HOST}
      CLIENT_ID: ${CLIENT_ID}
      REDIRECT_URL: ${REDIRECT_URL}
