name: Development
run-name: "${{ github.actor }} ran workflow on ${{ github.ref_name }}"
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  build_and_push:
    needs: lint
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build docker image
        run: docker build -t 'ghcr.io/${{ github.repository }}' .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Push to GitHub Container Registry
        run: docker push 'ghcr.io/${{ github.repository }}:latest'
