name: Feature
run-name: "${{ github.actor }} ran workflow on ${{ github.ref_name }}"
on:
  push:
    branches:
      - '\d+-*'
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml
    secrets:
      SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
