name: Feature
run-name: "${{ github.actor }} ran workflow on ${{ github.ref_name }}"
on:
  push:
    branches:
      - '\d+-*'
jobs:
  static_code_analysis:
    name: SonarCloud
    runs-on: ubuntu-22.04
    services:
      web:
        image: ghcr.io/leprec0n/web:latest
        ports:
          - 80:80
          - 443:443
        env:
          HOST: 0.0.0.0
          AUTH_HOST: ${{ secrets.AUTH_HOST }}
          CLIENT_ID: ${{ secrets.CIENT_ID }}
          GATEWAY_HOST: http://127.0.0.1:8080
          AUDIENCE: http://127.0.0.1:80
          CACHE_LOCATION: localstorage
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      account:
        image: ghcr.io/leprec0n/microservices/account:latest
        ports:
          - 8080:8080
        env:
          ACCOUNT_HOST: 0.0.0.0:8080
          LOG_LEVEL: debug
          ALLOW_ORIGIN: http://web:80
          DB_CONN: postgresql://postgres:postgres@127.0.0.1
          ACCOUNT_CONN: postgresql://postgres:postgres@127.0.0.1/account
          AUTH_HOST: ${{ secrets.AUTH_HOST }}
          CLIENT_ID_ACCOUNT: ${{ secrets.CLIENT_ID_ACCOUNT }}
          CLIENT_SECRET_ACCOUNT: ${{ secrets.CLIENT_SECRET_ACCOUNT }}
          CLIENT_AUD_ACCOUNT: ${{ secrets.CLIENT_AUD_ACCOUNT }}
          VALKEY_CONN: redis://127.0.0.1:6379
          SUB_NOT_VERIFIED: ${{ secrets.SUB_NOT_VERIFIED }}
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        options: --restart always
      account-db:
        image: postgres:16.2-alpine3.19
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      session-db:
        image: valkey/valkey:7.2-alpine3.19
        ports:
          - 6379:6379
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Install packages
        run: npm install --only=dev
      - name: End to end tests
        run: npx nyc --reporter=lcov cypress run
      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@49e6cd3b187936a73b8280d59ffd9da69df63ec9 # v2.1.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
