name: test
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: false
jobs:
  static_code_analysis:
    name: SonarCloud
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@49e6cd3b187936a73b8280d59ffd9da69df63ec9 # v2.1.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" # Needed to get PR information, if any
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
