name: test
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: false
jobs:
  static_code_analysis:
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    name: SonarCloud
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@49e6cd3b187936a73b8280d59ffd9da69df63ec9 # v2.1.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" # Needed to get PR information, if any
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
